### ISSUE TITLE
150 px transparent bar on the top side

### ISSUE THREAD

**Issue by albertopasqualetto** [jeffersonlicet/snipped#1]
Example:
![a](https://user-images.githubusercontent.com/39854348/124950013-57159f00-e012-11eb-9393-8476f69e4fda.png)
![image](https://user-images.githubusercontent.com/39854348/124949999-54b34500-e012-11eb-9217-4aa6b4e7924b.png)

**Comment by jeffersonlicet** [comment]
Thanks for the feedback. I'll fixed it ASAP

**Comment by jeffersonlicet** [comment]
Fixed.
