### ISSUE TITLE
How can I show only the file name instead of the full path?

### ISSUE THREAD

**Issue by hb20007** [jeffersonlicet/snipped#14]
I tried this extension but I see that the screenshot contains the whole path of the file:

![my screenshot](https://user-images.githubusercontent.com/8860322/148524714-30d2a2e5-0272-45b5-95be-24fccf654cd8.png)

I would like something similar to the examples on the extension page, where it's only the file name:

![example screenshot](https://user-images.githubusercontent.com/8860322/148522973-ebe2e114-0846-4c28-9543-4d861e3a83f0.png)

How can I get that?

**Comment by stephencombs** [comment]
Wondering the same thing. I definitely don't want to post screenshots with a full system file path.

**Comment by jeffersonlicet** [comment]
I'll fix this ASAP

**Comment by stephencombs** [comment]
> I'll fix this ASAP

Thank you for the prompt response!

**Comment by jeffersonlicet** [comment]
Should be working now
