### ISSUE TITLE
SVG output

### ISSUE THREAD

**Issue by 4086606** [jeffersonlicet/snipped#3]
While this extension is so useful, SVG brings many benefits, including small size, ability to upscale and the possibility of modifying the screenshot after taking it. Raster screenshots just don't cut it anymore on high DPI screens.

**Comment by 4086606** [comment]
Great, hope you can implement this soonish. Should be possible to insert VSC's token CSS in the SVG, get the gutter line color programmaticay then write the editor presentation tokens into the SVG.

**Comment by jeffersonlicet** [comment]
https://github.com/jeffersonlicet/snipped/pull/4
Closed with this PR. 
Thanks for the feedback!
