### ISSUE TITLE
Limit styles to non-default CSS

### ISSUE THREAD

**Issue by SNDST00M** [jeffersonlicet/snipped#5]
StackOverflow: https://stackoverflow.com/a/56408175/15764156

Aaaand it's an upstream issue. Will get it fixed and give y'all the 411

https://github.com/1904labs/dom-to-image-more/issues/36

**Comment by 4086606** [comment]
Aaaand it's an upstream issue. Will get it fixed and give y'all the 411

**Comment by SNDST00M** [comment]
@jeffersonlicet check out #8

**Comment by zm-cttae** [comment]
This is getting redone - can it be re-opened temporarily @jeffersonlicet ?

See 1904labs/dom-to-image-more#135
